name: LXD Tests

on:
  pull_request:
    branches:
      - master
      - devel
      - release/*
  push:
    branches:
      - devel
      - feature/cicd/restore-unsupported-release-targets

jobs:
  lxd:
    uses: ./.github/workflows/build-lxd.yml
    with:
      git_ref: "${{ github.ref }}"
